# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
