# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 23:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0007_descarga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('cuerpo', models.TextField(max_length=500)),
                ('fecha_enviado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Enviado')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Materia')),
                ('supervisor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='asesor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asesorado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('cuerpo', models.TextField(max_length=500)),
                ('fecha_enviado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Enviado')),
                ('supervisor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('cuerpo', models.TextField(max_length=500)),
                ('fecha_enviado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Enviado')),
                ('supervisor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipiente', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugeridor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='facultad',
            options={'verbose_name_plural': 'facultades'},
        ),
        migrations.AlterModelOptions(
            name='informacion',
            options={'verbose_name_plural': 'informaciones'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'perfiles'},
        ),
    ]
