# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0008_auto_20170701_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('cuerpo', models.TextField(max_length=500)),
                ('fecha_enviado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Enviado')),
                ('tipo', models.CharField(choices=[('A', 'Asesoría'), ('C', 'Contacto'), ('S', 'Sugerencia')], default='A', max_length=1)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Materia')),
                ('supervisor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipiente', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='asesoria',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='asesoria',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='asesoria',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sugerencia',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='sugerencia',
            name='user',
        ),
        migrations.DeleteModel(
            name='Asesoria',
        ),
        migrations.DeleteModel(
            name='Sugerencia',
        ),
    ]
