# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170702_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='carrera',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='escuela',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Escuela'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fallos_login',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='pregunta1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='pregunta2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='respuesta1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='respuesta2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
