# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20170702_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='pregunta1',
            field=models.CharField(choices=[('libro', '¿Cual es tu libro infantil favorito?'), ('cancion', '¿Cómo se llama tu canción favorita?'), ('abuelo', '¿Cómo se llama tu abuelo paterno?'), ('abuela', '¿Cómo se llama tu abuela materna?'), ('mascota', '¿Como se llamaba tu primera mascota?'), ('auto', '¿Cual es tu marca de autos preferida?')], default='libro', max_length=15),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='pregunta2',
            field=models.CharField(choices=[('libro', '¿Cual es tu libro infantil favorito?'), ('cancion', '¿Cómo se llama tu canción favorita?'), ('abuelo', '¿Cómo se llama tu abuelo paterno?'), ('abuela', '¿Cómo se llama tu abuela materna?'), ('mascota', '¿Como se llamaba tu primera mascota?'), ('auto', '¿Cual es tu marca de autos preferida?')], default='auto', max_length=15),
        ),
    ]
