# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 16:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20170707_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='cuerpo',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='titulo',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
