# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20170708_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='materia',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.Materia'),
        ),
    ]
