# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20170708_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipiente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
