# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20170708_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Pendiente', 'Pendiente'), ('Atendida', 'Atendida')], default='Libre', max_length=15),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('Asesoría', 'Asesoría'), ('Contacto', 'Contacto'), ('Sugerencia', 'Sugerencia')], default='Asesoría', max_length=15),
        ),
    ]
