# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20170708_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='esta_bloqueado',
            field=models.BooleanField(default=False),
        ),
    ]
