# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_perfil_esta_bloqueado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descarga',
            name='materia',
        ),
        migrations.DeleteModel(
            name='Descarga',
        ),
    ]
