# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20170720_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.CharField(default=None, max_length=20, null=True, unique=True),
        ),
    ]
