# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20170724_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacion',
            name='facultad',
        ),
        migrations.DeleteModel(
            name='Informacion',
        ),
    ]
