# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20170726_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='user',
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
