# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='user_avatars/default.gif', upload_to='user_avatars'),
        ),
    ]
